name: Devin Command

on:
  workflow_dispatch:
    inputs:
      # The following 2 inputs are always passed by the Slash Command Dispatch:
      comment-id:
        description: Comment ID. Optional.
        required: false
      issue-number:
        description: Issue Number. Optional.
        type: string
        required: false
      # Additional inputs for Devin-specific functionality:
      playbook-macro:
        description: "Playbook macro (Optional) - should start with '!' (e.g., !my_playbook)"
        type: string
        required: false
      prompt-text:
        description: "Custom prompt text (Optional)"
        type: string
        required: false

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run-devin-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Devin AI Action
        uses: ./
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          issue-number: ${{ github.event.inputs.issue-number }}
          playbook-macro: ${{ github.event.inputs.playbook-macro }}
          prompt-text: ${{ github.event.inputs.prompt-text }}
          devin-token: ${{ secrets.DEVIN_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
